
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhjcIQGlnLlIL80_dKl3ADNasKRtOfs54',
    appId: '1:199374179832:web:bc2cda6aa66e82abcf1a0d',
    messagingSenderId: '199374179832',
    projectId: 'saude-para-todos-adbcb',
    authDomain: 'saude-para-todos-adbcb.firebaseapp.com',
    storageBucket: 'saude-para-todos-adbcb.firebasestorage.app',
    measurementId: 'G-J5VE6DH7MR',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD37g8QE7LAmE8bFhOiWbk-IoKbj4znU4k',
    appId: '1:199374179832:ios:3c540519547dbc45cf1a0d',
    messagingSenderId: '199374179832',
    projectId: 'saude-para-todos-adbcb',
    storageBucket: 'saude-para-todos-adbcb.firebasestorage.app',
    iosBundleId: 'com.example.saudeParaTodos',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD37g8QE7LAmE8bFhOiWbk-IoKbj4znU4k',
    appId: '1:199374179832:ios:3c540519547dbc45cf1a0d',
    messagingSenderId: '199374179832',
    projectId: 'saude-para-todos-adbcb',
    storageBucket: 'saude-para-todos-adbcb.firebasestorage.app',
    iosBundleId: 'com.example.saudeParaTodos',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0iUvX6iyqGhh6Bt3Obn1bufGiF7PwGFk',
    appId: '1:199374179832:android:29d3b93844a182c3cf1a0d',
    messagingSenderId: '199374179832',
    projectId: 'saude-para-todos-adbcb',
    storageBucket: 'saude-para-todos-adbcb.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbTpnAcZhEBwsv40UEU1Wwm380R7hIWDo',
    appId: '1:199374179832:web:877026e4c7a65214cf1a0d',
    messagingSenderId: '199374179832',
    projectId: 'saude-para-todos-adbcb',
    authDomain: 'saude-para-todos-adbcb.firebaseapp.com',
    storageBucket: 'saude-para-todos-adbcb.firebasestorage.app',
    measurementId: 'G-ERXGK89GR5',
  );

}